name: Testing Lex
on: push
jobs:
  test:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Checkout our code
      uses: actions/checkout@v2.4.2
    - name: Setup PHP
      uses: shivammathur/setup-php@2.21.1
      with:
        php-version: 8.1
        extensions: grpc
    - run: composer update
    - name: Test the code
      run: ./vendor/bin/phpunit tests/OperationsTest.php