name: Testing Lex
on: push
jobs:
  test:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Verify pre checkout
      run: ls
    - name: Checkout our code
      uses: actions/checkout@v2.4.2
    - name: Verify
      run: ls